### PR TITLE
Feature/quay docker publish

### PR DESCRIPTION
**Pull request by PI-Victor**

### CODE REVIEW

**Comment by PI-Victor** [comment]
definitely not sure why it says there are conflicting files... :/

**Review by jw-s — CHANGES_REQUESTED** [review]
Please change `vastness.io` to `vastness`

**Comment by PI-Victor** [comment]
done

**Comment by jw-s** [comment]
@PI-Victor Can you sort the conflicts please

**Comment by PI-Victor** [comment]
@jw-s it should be good now.

**Comment by PI-Victor** [comment]
@jw-s can you merge this?

**Pull request merged**
